version: "3.8"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./docker-compose/pgsql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: db
    networks:
      - attendance-network

  attendance:
    image: attendance
    build:
      context: attendance
      dockerfile: Dockerfile    
    ports:
      - "8082:8080"
    networks:
      - attendance-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/attendance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    container_name: attendance
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./attendance-fr/dist:/var/www/ui
    networks:
      - attendance-network
    depends_on:
      - attendance
      - register


networks:
  attendance-network:
    driver: bridge
